services:
  app:
    image: post-service:local
    container_name: ps-app
    depends_on:
      - postgresql
    ports:
      - "8082:8082"

  postgresql:
    image: postgres:14-alpine
    container_name: ps-psql
    environment:
      - POSTGRES_DB=url_shortener
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"